### ISSUE TITLE
font icon glyph missing 

### ISSUE THREAD

**Issue by noornee** [kopecmaciej/vi-mongo#28]
Hello, the font that is being used by `vi-mongo` is missing on my machine.

![image](https://github.com/user-attachments/assets/9b92e4a0-3de7-4d89-a117-2bd640c02cc8)

could you provide the font name so i could install it?. thanks!

**Comment by noornee** [comment]
sheesh, just went through the styles config and saw that i could customize the symbol.

**Comment by kopecmaciej** [comment]
Hi @noornee , I'm using `noto-fonts` with kitty terminal (it looks realy good for me):
![Screenshot_2024-10-30-10-46-44_30574](https://github.com/user-attachments/assets/3b58f47e-eb12-4c7f-a9da-d2dd0eadb9e4)
but I know that `ttf-Symbola` is also a way to install them.
Also in welcome page there was a button to turn on/off better-looking symbols
![Screenshot_2024-10-30-10-47-41_1628](https://github.com/user-attachments/assets/6ec492d8-b0e9-4082-9299-679f5edca987)
If you didn't notice it maybe I should make it more visable for the user?

**Comment by noornee** [comment]
> Hi @noornee , I'm using `noto-fonts` with kitty terminal (it looks realy good for me): 

Hii @kopecmaciej
ooh, i dont have that installed on my machine. I'll try it out. I use Iosevka Nerd Font on kitty

> If you didn't notice it maybe I should make it more visable for the user?

No, i think its okay where it is. I actually did notice it but i was more focused on finding out why the font glyph was missing. it didnt occur to me that it could be turned off

![image](https://github.com/user-attachments/assets/2873776d-2cba-40a3-b5fe-b1a98152a3ce)

just toggled it off, saved and connected. the default font it provides looks great!
