### ISSUE TITLE
feature request: hide/show column in a collection view

### ISSUE THREAD

**Issue by astahjmo** [kopecmaciej/vi-mongo#37]
Hello! I think it would be useful to have a new keybinding and feature that allows users to hide or show specific columns in a document list. This would provide more flexibility in organizing and viewing content based on individual preferences.

**Comment by kopecmaciej** [comment]
Hi @astahjmo , sorry for late response, this seems like a nice feature, although it requires little bit of work as there are multiple ways of viewing documents, so I will have to keep this in mind, but I will take a look into code base and see how to implement this as easy as possible

**Comment by kopecmaciej** [comment]
Feature was implemented in v0.1.20, so for now I'm closing as completed
